### ISSUE TITLE
Seems that this module is non more compliant to the R3.x companion-SW as well as to the DCC-EX 5.x SW

### ISSUE THREAD

**Issue by energiebrand** [daniep01/companion-module-dcc-ex-commandstation#1]
I used an Elgato StreamDeck XL sending simple text- commands via the DCC-Ex Installer Device Monitor or WebThrotte. 
Then I found the companion and the DCC-EX module. However ist seems that this projet is abanded and some commands do not run anymore or are not complete. Would be nice to hear if it will continoue in the future...

**Comment by daniep01** [comment]
Thanks for reaching out, I'm happy to update the module if you would find it useful

**Comment by energiebrand** [comment]
Hello Peter, thank you very much for your answer. I didn't expect that at all, after the project had been lying dormant here in Github for probably 3 years. A few days ago I had a short conversation in the DCC-EX Discord channel with one of the developers of DCC-EX -> UKBloke (Chris). He likes this application, but doesn't have a StreamDeck himself. I have offered to test and help if necessary if anyone there wants to restart or continue development. If you are still willing to invest in development work here, I would very much welcome it and also report and advertise a bit in the DCC-EX Discord if you are not still active there yourself. I think a few commands have changed their synthax or have been added. I also tried configuring the throttle function in the module, but unfortunately that didn't work. I don't know if I did something wrong or if this feature wasn't fully implemented. I also get a warning from the companion that the DCC-EX module is not compatible with V3 and probably only works to a limited extent. So thank you very much and it would be great if you could take a look at the module again.
Greetings
Hartmut
